version: "3.9"
services:
  db:
    image: postgres:16
    container_name: thmanyah_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: thmanyah
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d thmanyah"]
      interval: 3s
      timeout: 3s
      retries: 10

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: thmanyah_api
    environment:
      PORT: 3001
      DATABASE_URL: postgresql://postgres:postgres@db:5432/thmanyah?schema=public
      CORS_ORIGIN: http://localhost:3000
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:3001
    container_name: thmanyah_web
    environment:
      NODE_ENV: production
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  dbdata:
